### ISSUE TITLE
Feature: Import existing solved/attempted statistics 

### ISSUE THREAD

**Issue by suramrit** [LorenzoBe/LeetPlug#3]
I wonder if there is a way to import existing statistics for a user onto the leetplug dashboard. It would help people keep track of their already made progress rather than starting from fresh.

**Comment by suramrit** [comment]
I know that theres already a cli that can do the login+get statistics for a lc user: https://skygragon.github.io/leetcode-cli/commands#stat

**Comment by LorenzoBe** [comment]
Wow! Thanks for pointing to the CLI, I didn't know about it! I think the maintainer has a very good connection with LeetCode and did a great job!
However the important part of LeetPlug is to track how long people took to solve a problem and I don't think this is stored inside LeetCode. So the only thing that we could extract from LeetCode is maybe the list of solved questions, without any detail about when and finish time. I think it is better to wait that LeetCode will implement the LeetPlug features directly in their site, so I can close the project :D

**Comment by suramrit** [comment]
Im sure leetplug played a significant role in making that happen! :)
